#!/bin/sh

#
# This disallows committing mismatched files.
#
# Let's hope developers notice if so, and don't lose work.
#

if ! diff -q "js/adj.js" "user-docs/.adj-js/adj.js" > /dev/null
then
    echo "WILL NOT COMMIT MISMATCHED js/adj.js VERSUS user-docs/.adj-js/adj.js'"
    echo "MUST FIX BEFORE TRYING TO COMMIT AGAIN"
    exit 1
fi

exit 0
